name: Linting, testing, building
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]
jobs:
  pipline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: add modules
        run: yarn add
      - name: build production project
        run: yarn build:prod
      - name: linting typescript
        run: yarn lint:ts
      - name: unit testing
        run: yarn test:unit
